### ISSUE TITLE
Open API spec for routing service admin API

### ISSUE THREAD

**Issue by adrianhopebailie** [mojaloop/contrib-cross-network-demo#1]
## **Goal**:
As an implementor I want to have an Open API specification for the admin API on the routing service so that I can manage routes and peers.

**Tasks**:
- [x] Define API endpoint for add/remove route
- [x] Define API endpoint for add/remove peer
- [x] Define API endpoint for get next hop
 
**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @adrianhopebailie 
- QA/Review: @matdehaast / @DonChangfoot

**Comment by elnyry-sam-k** [comment]
Closing as outdated; please re-open when this becomes active again and if needed
