### ISSUE TITLE
PoC Routing Service Implementation

### ISSUE THREAD

**Issue by matdehaast** [mojaloop/contrib-cross-network-demo#3]
## **Goal**:
As a Hub Operator I want to a service to query which will determine where to route a quote or payment request.

As a Hub Operator I want a service which can broadcast routing messages

As a Hub Operator I want a service which can receive incoming route broadcast messages to update my routing logic

**Tasks**:
- [x] Create Project structure for Routing Service
- [x] Implement API endpoints as per the design specification https://github.com/mojaloop/cross-network/issues/1 
- [x] Dockerize the service
- [x] Add to Helm Repo definition for deployment on cross-network branch

**Acceptance Criteria**:
- [x] API must be able to:
    - [x] Can query endpoints for nextHop
    - [x] Can send/receive route updates
    - [x] Can add/remove peers
- [x] Designs are up-to date
- [x] Unit Tests pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- https://github.com/mojaloop/cross-network/issues/1

## **Accountability**:
- Owner: @matdehaast 
- QA/Review: @adrianhopebailie @DonChangfoot

**Comment by elnyry-sam-k** [comment]
Closing as this hasn't been touched in a few years; please re-open when this becomes active again and if needed
